
# Import Libraries and Functions

Remember to run 'Functions.Rmd' before this script!

```{r paths}
DEPMAP_FILES_FOLDER <- "./"
COMMON_GENES_FILE <- "ShinyData/common_genes.txt"
PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX <- "ShinyData/MUT/Pan/"
CANCER_SPECIFIC_DRIVER_GENE_ANALYSIS_PREFIX <- "ShinyData/MUT/Specific/"
PATHWAY_ANALYSIS_PREFIX <- "ShinyData/Expression/"

```

# Read Stored Public Data (DepMap, Surfaceome, MSigDB)

```{r read DepMap data}
TPM <- read_EH_file("TPM", DEPMAP_FILES_FOLDER)
CRISPR <- read_EH_file("CRISPR", DEPMAP_FILES_FOLDER)
METADATA <- read_EH_file("METADATA", DEPMAP_FILES_FOLDER)
MUT <- read_EH_file("MUT", DEPMAP_FILES_FOLDER)

row.names(METADATA) <- METADATA$depmap_id

```

```{r read gene sets from MSigDB}
oncogenic_gene_sets <- msigdbr(species = "Homo sapiens", category = "C6")
gene_sets <- as.list(unique(oncogenic_gene_sets$gs_name))
names(gene_sets) <- gene_sets

approved_genes <- intersect(unique(TPM$gene_name), unique(oncogenic_gene_sets$gene_symbol))

for (gs in gene_sets) {
  gene_sets[gs] <- as.list((oncogenic_gene_sets %>%
                              filter(gs_name == gs) %>%
                              filter(gene_symbol %in% approved_genes))
                           ["human_gene_symbol"])
}

```

```{r read drugable genes from DepMap}
druggable_genes <- read.csv(paste(DEPMAP_FILES_FOLDER,"Corsello.csv",sep=""))
druggable_genes <- unique(unlist(strsplit(druggable_genes$target, ", ")))
druggable_genes <- na.omit(druggable_genes)
```

# Read Stored SLICE Data

```{r read driver genes (Pan-cancer)}
common_genes <- read_lines(COMMON_GENES_FILE)

```

```{r read DD and P-value data for driver-gene-oriented analysis}
# Pan-cancer level
lfc_matrix <- as.matrix(read.csv(paste(PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX,"lfc_matrix.csv",sep="")))
pvalue_matrix <- as.matrix(read.csv(paste(PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX,"pvalue_matrix.csv",sep="")))

# Cancer-specific level
mut_spec_lfcs <- list()
mut_spec_pvalues <- list()

cancer_types_filt <- c("Liver Cancer", "Head and Neck Cancer", "Kidney Cancer", "Lymphoma", "Gastric Cancer", "Brain Cancer", "Myeloma", "Pancreatic Cancer", "Breast Cancer", "Skin Cancer", "Ovarian Cancer", "Lung Cancer", "Bladder Cancer", "Colon/Colorectal Cancer", "Leukemia")
primary_disease <- gsub("/", " ", cancer_types_filt)

for(current_cancer_type in primary_disease){
  mut_spec_lfcs[[current_cancer_type]] <- as.matrix(read.csv(
    paste(CANCER_SPECIFIC_DRIVER_GENE_ANALYSIS_PREFIX,"lfc_",
          current_cancer_type, ".csv", sep="")))
  mut_spec_pvalues[[current_cancer_type]] <- as.matrix(read.csv(
    paste(CANCER_SPECIFIC_DRIVER_GENE_ANALYSIS_PREFIX,"pvalue_",
          current_cancer_type, ".csv", sep="")))
}

```

```{r read Correlation and P-value data for pathway-enrichment-oriented analysis}
correlation_dfs <- list()

primary_disease <- gsub("/", " ", unique(METADATA$primary_disease))
excluded_values <- c("Endometrial Uterine Cancer", "Unknown", "Adrenal Cancer", "Embryonal Cancer", "Teratoma", "Non-Cancerous", "Fibroblast", "Prostate Cancer")
filtered_primary_disease <- subset(primary_disease, !primary_disease %in% excluded_values)

# Cancer-specific level
for(current_cancer_type in filtered_primary_disease){
  correlation_dfs[[current_cancer_type]] <- read.csv(
    paste(PATHWAY_ANALYSIS_PREFIX,"Specific/",
          current_cancer_type, "_corr.csv", sep=""))[,2:5]
}

# Pan-cancer level
correlation_dfs[["pan"]] <- read.csv(
    paste(PATHWAY_ANALYSIS_PREFIX,"Pan/dependency_corr.csv", sep=""))[,2:5]
  
```

```{r read dependency profiles and targetable dependency profiles}
# Pan-cancer level
dependencyProfile_matrix <- as.matrix(read.csv(paste(PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX,
                                                     "dependencyProfile_matrix.csv",sep="")))
dependencyProfile_targetable_matrix <- as.matrix(read.csv(paste(PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX,
                                                                "dependencyProfile_targetable_matrix.csv", sep="")))
mutation_matrix <- as.matrix(read.csv(paste(PAN_CANCER_DRIVER_GENE_ANALYSIS_PREFIX,
                                            "mutation_matrix.csv",sep="")))

# Cancer-specific level
mut_spec_dependencyProfiles <- list()
mut_spec_dependencyProfiles_targetable <- list()

primary_disease <- gsub("/", " ", cancer_types_filt)

for(current_cancer_type in primary_disease){
  mut_spec_dependencyProfiles[[current_cancer_type]] <- as.matrix(read.csv(
    paste(CANCER_SPECIFIC_DRIVER_GENE_ANALYSIS_PREFIX,"dependencyProfile_",
          current_cancer_type, ".csv", sep="")))
  mut_spec_dependencyProfiles_targetable[[current_cancer_type]] <- as.matrix(read.csv(
    paste(CANCER_SPECIFIC_DRIVER_GENE_ANALYSIS_PREFIX,"dependencyProfile_targetable_",
          current_cancer_type, ".csv", sep="")))
}

```

# Notify me on Slack that the run has finished

```{r send message to slack, eval=FALSE, include=FALSE}
msg <- list(text=paste("shinySLICE - data loading completed:", toc()[4]))
webhook <- "???"
POST(webhook, encode = "json", body = msg)

```
